spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Security OAuth2
  security:
    oauth2.client:
      registration:
        google:
          clientId: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_SECRET}
          scope:
            - email
            - profile
        naver:
          client-id: r6myU9ARNh3UD4spf1tJ
          client-secret: OicBRO_kJr
          scope:
            - nickname
            - email
            - profile_image
          client-name: Naver
          authorization-grant-type: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        kakao:
          client-id: 7c0426d5fb2f7bdfcd38068a7b300311
          client-secret: TdAEQ33OLlljgQXGvMwar217ghZxfWOh
          authorization-grant-type: authorization_code
          client-authentication-method: POST
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope: profile_nickname, profile_image, account_email
          client-name: Kakao
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user_name_attribute: response
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

